#!/bin/bash

set -e

if ! command -v paru &>/dev/null; then
    echo "󰖷 paru not found. Installing paru..."
    temp_dir=$(mktemp -d)
    git clone --depth 1 https://aur.archlinux.org/paru-bin.git "$temp_dir" &>/dev/null
    (
        cd "$temp_dir"
        makepkg -si --noconfirm --quiet &>/dev/null
    )
    rm -rf "$temp_dir"
    echo " paru installed successfully."
fi

packages=(
    adwsteamgtk
    brightnessctl
    bibata-cursor-theme-bin
    chafa
    eza
    grim
    hyprland
    hyprlock
    hyprshot
    hyprpaper
    inotify-tools
    kitty
    kvantum
    kvantum-qt5
    libnotify
    lf
    mako
    nemo
    nemo-fileroller
    neovim
    oh-my-posh-bin
    pavucontrol
    rofi-emoji
    rofi-wayland
    slurp
    upower
    waybar
    wlogout
    xdg-desktop-portal-wlr
    xdg-desktop-portal-hyprland
    zen-browser-bin
    zoxide
    zsh
)

for package in "${packages[@]}"; do
    if pacman -Q "$package" &>/dev/null; then
        echo " $package is already installed."
    else
        echo "󰏗 Installing $package..."
        if paru -S --noconfirm --quiet "$package" &>/dev/null; then
            echo " Successfully installed $package."
        else
            echo " Failed to install $package." >&2
        fi
    fi
done

if [ "$SHELL" != "/usr/bin/zsh" ]; then
    echo "󰖷 Setting zsh as the default shell.."
    echo -n "[sudo] password for $USER: "
    chsh -s $(which zsh) &>/dev/null
    echo -e "\n  zsh has been set as the default shell."
else
    echo -e " zsh is already the default shell."
fi
