#!/bin/bash

set -e

# Chaotic AUR Setup
if ! grep -q "\[chaotic-aur\]" /etc/pacman.conf; then
    echo "󰖷 Setting up Chaotic AUR..."

    # Import and sign the Chaotic AUR key
    sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
    sudo pacman-key --lsign-key 3056513887B78AEB

    # Install the keyring and mirrorlist
    sudo pacman -U --noconfirm --needed \
      'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' \
      'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

    # Add chaotic-aur to pacman.conf if not already present
    echo -e "\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist" | sudo tee -a /etc/pacman.conf > /dev/null

    echo " Chaotic AUR added successfully."
else
    echo " Chaotic AUR is already configured."
fi

# List of packages to install
packages=(
    auto-cpufreq
    rog-control-center
    supergfxctl
    tlp
    tlp-rdw
)

# Install packages
for package in "${packages[@]}"; do
    if pacman -Q "$package" &>/dev/null; then
        echo " $package is already installed."
    else
        echo "󰏗 Installing $package..."
        if sudo pacman -S --noconfirm --quiet --overwrite='*' "$package" &>/dev/null; then
            echo " Successfully installed $package."

    # Enable services if needed
    case "$package" in
        auto-cpufreq)
            echo "󰈆 Enabling and starting auto-cpufreq..."
            systemctl enable --now auto-cpufreq
            ;;
        tlp)
            echo "󰈆 Enabling and starting tlp..."
            systemctl enable --now tlp
            ;;
    esac
else
    echo " Failed to install $package." >&2
        fi
    fi
done
