#!/bin/bash

set -e

# AUR Setup
if command -v paru >/dev/null 2>&1; then
    echo "󰋑 paru is already installed."
else
    echo "󰏗 Installing paru.."
    git clone https://aur.archlinux.org/paru-bin.git >/dev/null 2>&1
    cd paru-bin >/dev/null 2>&1
    makepkg -si --noconfirm >/dev/null 2>&1
    cd .. >/dev/null 2>&1
    rm -rf paru-bin >/dev/null 2>&1
    echo " paru installation complete."
fi
if ! grep -q "\[chaotic-aur\]" /etc/pacman.conf; then
    echo "󰖷 Setting up Chaotic AUR..."
    {
        sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
        sudo pacman-key --lsign-key 3056513887B78AEB
        sudo pacman -U --noconfirm --needed \
            'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' \
            'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
        echo -e "\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist" | sudo tee -a /etc/pacman.conf > /dev/null
        sudo pacman -Sy
    } &> /dev/null
echo " Chaotic AUR added successfully."
else
    echo "󰋑 Chaotic AUR is already configured."
fi

# List of packages to install
packages=(
    auto-cpufreq
    acpi_call
    rog-control-center
    supergfxctl
    tlp
    tlp-rdw
    upower
)

# Install packages
for package in "${packages[@]}"; do
    if pacman -Q "$package" &>/dev/null; then
        echo "󰋑 $package is already installed."
    else
        echo "󰏗 Installing $package..."
        if paru -S --noconfirm --quiet "$package" &>/dev/null; then
            echo -e " Successfully installed $package.\n"

    # Enable services if needed
    case "$package" in
        auto-cpufreq)
            echo "󰈆 Enabling and starting auto-cpufreq..."
            systemctl enable --now auto-cpufreq &>/dev/null
            ;;
        asusctl)
            echo "󰈆 Enabling and starting asusd..."
            systemctl enable --now asusd &>/dev/null
            ;;
        supergfxctl)
            echo "󰈆 Enabling and starting asusd..."
            systemctl enable --now supergfxd &>/dev/null
            ;;
        tlp)
            echo "󰈆 Enabling and starting tlp..."
            systemctl enable --now tlp &>/dev/null
            ;;
    esac
else
    echo " Failed to install $package." >&2
        fi
    fi
done
