#!/bin/bash

set -e

# AUR Setup
if command -v paru >/dev/null 2>&1; then
    echo "󰋑 paru is already installed."
else
    echo "󰏗 Installing paru.."
    git clone https://aur.archlinux.org/paru-bin.git >/dev/null 2>&1
    cd paru-bin >/dev/null 2>&1
    makepkg -si --noconfirm >/dev/null 2>&1
    cd .. >/dev/null 2>&1
    rm -rf paru-bin >/dev/null 2>&1
    echo " paru installation complete."
fi
if ! grep -q "\[chaotic-aur\]" /etc/pacman.conf; then
    echo "󰖷 Setting up Chaotic AUR..."

    # Import and sign the Chaotic AUR key
    sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
    sudo pacman-key --lsign-key 3056513887B78AEB

    # Install the keyring and mirrorlist
    sudo pacman -U --noconfirm --needed \
      'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' \
      'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

    # Add chaotic-aur to pacman.conf if not already present
    echo -e "\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist" | sudo tee -a /etc/pacman.conf > /dev/null

    echo " Chaotic AUR added successfully."
else
    echo "󰋑 Chaotic AUR is already configured."
fi

# List of packages to install
packages=(
    autotiling-git
    bat
    brightnessctl
    bibata-cursor-theme
    chafa
    eza
    grim
    hyprlock
    hyprshot
    inotify-tools
    kvantum
    kvantum-qt5
    libnotify
    mako
    nautilus
    file-roller
    neovim
    nwg-look
    pavucontrol
    qt5ct
    qt6ct
    rofi-emoji
    rofi-wayland
    sway
    swayosd
    swaybg
    slurp
    tlp
    upower
    waybar
    xdg-desktop-portal-wlr
    xdg-desktop-portal-hyprland
    zen-browser-bin
    zoxide
    zsh
    yazi
)

# Install packages
for package in "${packages[@]}"; do
    if pacman -Q "$package" &>/dev/null; then
        echo "󰋑 $package is already installed."
    else
        echo -e "󰏗 Installing $package..."
        if paru -S --noconfirm --quiet "$package" &>/dev/null; then
            echo -e " Successfully installed $package.\n"

    # Enable services if needed
    case "$package" in
        auto-cpufreq)
            echo "󰈆 Enabling and starting hyprpolkitagent..."
            systemctl --user enable --now hyprpolkitagent.service &>/dev/null
            ;;
    esac
else
    echo " Failed to install $package." >&2
        fi
    fi
done

# Set zsh as the default shell if it's not already set
if [ "$SHELL" != "/usr/bin/zsh" ]; then
    echo "󰖷 Setting zsh as the default shell..."
    echo -n "[sudo] password for $USER: "
    chsh -s $(which zsh) &>/dev/null
    echo -e "\n  zsh has been set as the default shell."
else
    echo -e "󰋑 zsh is already the default shell."
fi
