require("config.lazy")
require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.plugins.telescope")
require("config.plugins.neo-tree")
require("config.plugins.lualine")
require("config.plugins.noice")

require("colors.theme")
require("colors.syntax")
