[colors]
primary.background = "#1e1e20"
primary.foreground = "#d3d3d5"

[colors.bright]
black = "#666666"
blue = "#72949a"
cyan = "#729a96"
green = "#729a72"
magenta = "#8c729a"
red = "#976061"
white = "#f1f1f1"
yellow = "#a49a72"

[colors.normal]
black = "#1e1e20"
blue = "#5f7a8c"
cyan = "#5f7a7f"
green = "#5f7a5f"
magenta = "#75607a"
red = "#865054"
white = "#d3d3d5"
yellow = "#a4965f"
