listener {
    timeout = 180                            # in seconds.
    on-timeout = notify-send "Where have you gone.." # command to run when timeout has passed.
    on-resume = notify-send "Welcome back!"  # command to run when activity is detected after timeout has fired.
}
