background {
    monitor = *
    path = screenshot
    blur_size = 10
    blur_passes = 2
}

label {
    monitor = *
    text = $TIME
    font_size = 64
    color = ffffff
    position = 0, 0
    halign = center
    valign = center
}

general {
    hide_cursor = true
}

