#!/bin/bash

# Define power menu options
options=(
    "󰐥 Shutdown"
    "󰜉 Reboot"
    "󰌾 Lock"
    "󰽥 Suspend"
    "󰍃 Logout"
)

# Present the menu using tofi
choice="$(printf '%s\n' "${options[@]}" | tofi --prompt-text='' --min-input-width='690' --hide-input=true --late-keyboard-init)"

# Execute the selected option
case "$choice" in
    "󰐥 Shutdown")
        systemctl poweroff
        ;;
    "󰜉 Reboot")
        systemctl reboot
        ;;
    "󰌾 Lock")
        if command -v gtklock >/dev/null; then
            gtklock
        elif command -v hyprlock >/dev/null; then
            hyprlock
        elif command -v i3lock >/dev/null; then
            i3lock
        elif command -v betterlockscreen >/dev/null; then
            betterlockscreen -l
        else
            notify-send "No lock utility found."
        fi
        ;;
    "󰽥 Suspend")
        systemctl suspend
        ;;
    "󰍃 Logout")
        pkill -KILL -u "$USER"
        ;;
esac
