#!/bin/bash

BATTERY_DEVICE=$(upower -e | grep BAT)
KBD_DEVICE="asus::kbd_backlight"
current_state=""

upower --monitor | grep --line-buffered "changed.*$BATTERY_DEVICE" | while read -r line; do
    new_state=$(upower -i "$BATTERY_DEVICE" | grep -m1 "state:" | awk '{print $2}')
    if [ "$new_state" != "$current_state" ]; then
        current_state="$new_state"
        current_brightness=$(brightnessctl get)
        if [ "$new_state" = "discharging" ]; then
            if [ "$current_brightness" != "40" ]; then
                brightnessctl set 40%
                brightnessctl --device="$KBD_DEVICE" set 0
            fi
            swaymsg output eDP-1 mode 1920x1080@60Hz
        else
            if [ "$current_brightness" != "80" ]; then
                brightnessctl set 80%
                brightnessctl --device="$KBD_DEVICE" set 80%
            fi
            swaymsg output eDP-1 mode 1920x1080@144Hz
        fi
    fi
done &
