#!/bin/bash

# Get Volume
get_volume() {
    volume=$(pamixer --get-volume)
    echo "$volume"
}

# Build Volume Bar
get_volume_bar() {
	volume=$(get_volume)
	blocks=$((volume / 5))
	bar=" "
	for ((i = 0; i < 20; i++)); do
		if [ $i -lt $blocks ]; then
			bar+="<span foreground='#a4965f'>▄ </span>"
		else
			bar+="<span foreground='#3f4044'>▄ </span>"
		fi
	done
	bar+=" "
	echo "$bar"
}

# Notify
notify_user() {
    bar=$(get_volume_bar)
    volume=$(get_volume)
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Volume ($volume%)" "$bar"
}

# Increase Volume
inc_volume() {
    pamixer -i 5 && notify_user
}

# Decrease Volume
dec_volume() {
    pamixer -d 5 && notify_user
}

# Toggle Mute
toggle_mute() {
    if [ "$(pamixer --get-mute)" == "false" ]; then
        pamixer -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Volume (muted)" "$bar"
    elif [ "$(pamixer --get-mute)" == "true" ]; then
        pamixer -u && notify_user
    fi
}

# Execute accordingly
case "$1" in
    --get) get_volume ;;
    --inc) inc_volume ;;
    --dec) dec_volume ;;
    --toggle) toggle_mute ;;
    *) get_volume ;;
esac
